"""initial schema

Revision ID: 4ced0c4116e9
Revises: 
Create Date: 2026-08-13 02:57:03.577765
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4ced0c4116e9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('school_name', sa.String(length=200), nullable=False),
    sa.Column('email_domain', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'SETUP', 'APPLICATIONS_OPEN', 'TEAM_FORMATION', 'REGISTRATION_LOCKED', 'PRE_TRYOUT', 'TRYOUT_ACTIVE', 'RESULTS', 'CLEANUP', 'ARCHIVED', name='eventstate', native_enum=False, length=32), server_default='DRAFT', nullable=False),
    sa.Column('applications_open_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applications_close_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('team_creation_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruitment_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tryout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cleanup_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_index('uq_events_active_per_guild', 'events', ['guild_id'], unique=True, postgresql_where=sa.text("state <> 'ARCHIVED'"))
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=True),
    sa.Column('default_roster_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games')),
    sa.UniqueConstraint('name', name=op.f('uq_games_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discord_user_id', sa.BigInteger(), nullable=False),
    sa.Column('discord_username', sa.String(length=100), nullable=False),
    sa.Column('discord_display_name', sa.String(length=100), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('discord_user_id', name=op.f('uq_users_discord_user_id'))
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', name='auditresult', native_enum=False, length=10), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_audit_logs_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_event_created', 'audit_logs', ['event_id', 'created_at'], unique=False)
    op.create_table('discord_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.Enum('ROLE', 'CATEGORY', 'TEXT_CHANNEL', 'VOICE_CHANNEL', 'FORUM_CHANNEL', 'STAGE_CHANNEL', 'FORUM_POST', 'MESSAGE', name='resourcetype', native_enum=False, length=20), nullable=False),
    sa.Column('discord_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_type', sa.Enum('EVENT', 'GAME', 'TEAM', 'SYSTEM', 'LOG', name='resourceownertype', native_enum=False, length=16), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CREATED', 'DELETING', 'DELETED', 'MISSING', name='resourcestatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_discord_resources_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discord_resources'))
    )
    op.create_index('ix_resource_lookup', 'discord_resources', ['event_id', 'owner_type', 'owner_id', 'purpose'], unique=False)
    op.create_table('event_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('roster_size', sa.Integer(), nullable=False),
    sa.Column('challonge_url', sa.String(length=500), nullable=True),
    sa.Column('tryout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stage_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_games_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_event_games_game_id_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_games')),
    sa.UniqueConstraint('event_id', 'game_id', name='event_game')
    )
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('export_type', sa.String(length=40), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_exports_event_id_events')),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], name=op.f('fk_exports_generated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports'))
    )
    op.create_table('recruitment_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ign', sa.String(length=100), nullable=False),
    sa.Column('main_role', sa.String(length=100), nullable=True),
    sa.Column('profile_screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('stats_screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='recruitmentpoststatus', native_enum=False, length=16), server_default='OPEN', nullable=False),
    sa.Column('forum_post_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_recruitment_posts_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_recruitment_posts_game_id_games')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_recruitment_posts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_posts'))
    )
    op.create_table('staff_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('staff_role', sa.Enum('HEAD', 'COMMITTEE', 'OIC', 'FIC', name='staffrole', native_enum=False, length=16), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_staff_assignments_assigned_by_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_staff_assignments_event_id_events')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_assignments_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_assignments'))
    )
    op.create_index('uq_staff_active', 'staff_assignments', ['event_id', 'user_id', 'staff_role'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('leader_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('RECRUITING', 'FULL', 'REGISTERED', 'CHECKED_IN', 'COMPETING', 'ELIMINATED', 'CHAMPION', 'DISBANDED', name='teamstatus', native_enum=False, length=16), server_default='RECRUITING', nullable=False),
    sa.Column('roster_size', sa.Integer(), nullable=False),
    sa.Column('disbanded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_teams_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_teams_game_id_games')),
    sa.ForeignKeyConstraint(['leader_user_id'], ['users.id'], name=op.f('fk_teams_leader_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('event_id', 'game_id', 'name', name='name')
    )
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('middle_initial', sa.String(length=10), nullable=True),
    sa.Column('school_email', sa.String(length=255), nullable=False),
    sa.Column('facebook_url', sa.String(length=500), nullable=False),
    sa.Column('year_section', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'ASSIGNED_TO_TEAM', 'DISQUALIFIED', name='applicationstatus', native_enum=False, length=24), server_default='PENDING', nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'REJECTED' OR rejection_reason IS NOT NULL", name=op.f('ck_applications_rejection_reason_required')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_applications_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_applications_game_id_games')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('fk_applications_reviewed_by_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_applications_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications'))
    )
    op.create_index('uq_app_active_per_email', 'applications', ['event_id', 'school_email'], unique=True, postgresql_where=sa.text("status IN ('PENDING','APPROVED','ASSIGNED_TO_TEAM')"))
    op.create_index('uq_app_active_per_user', 'applications', ['event_id', 'user_id'], unique=True, postgresql_where=sa.text("status IN ('PENDING','APPROVED','ASSIGNED_TO_TEAM')"))
    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('CHECKED_IN', 'NOT_CHECKED_IN', 'EXCUSED', 'OVERRIDDEN', name='checkinstate', native_enum=False, length=20), server_default='NOT_CHECKED_IN', nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_checkins_actor_user_id_users')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_checkins_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_checkins_game_id_games')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_checkins_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_checkins_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins')),
    sa.UniqueConstraint('team_id', 'user_id', name='team_user')
    )
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('team_a_id', sa.Integer(), nullable=False),
    sa.Column('team_b_id', sa.Integer(), nullable=True),
    sa.Column('winner_team_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'READY', 'LIVE', 'COMPLETED', 'CANCELLED', 'DISPUTED', name='matchstatus', native_enum=False, length=16), server_default='SCHEDULED', nullable=False),
    sa.Column('voice_channel_ref', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_matches_event_id_events')),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name=op.f('fk_matches_game_id_games')),
    sa.ForeignKeyConstraint(['team_a_id'], ['teams.id'], name=op.f('fk_matches_team_a_id_teams')),
    sa.ForeignKeyConstraint(['team_b_id'], ['teams.id'], name=op.f('fk_matches_team_b_id_teams')),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], name=op.f('fk_matches_winner_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches'))
    )
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_game_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_mechanics_created_by_users')),
    sa.ForeignKeyConstraint(['event_game_id'], ['event_games.id'], name=op.f('fk_mechanics_event_game_id_event_games')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mechanics')),
    sa.UniqueConstraint('event_game_id', 'version', name='event_game_version')
    )
    op.create_table('recruitment_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recruitment_post_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='recruitrequeststatus', native_enum=False, length=16), server_default='PENDING', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recruitment_post_id'], ['recruitment_posts.id'], name=op.f('fk_recruitment_requests_recruitment_post_id_recruitment_posts')),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name=op.f('fk_recruitment_requests_requested_by_users')),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], name=op.f('fk_recruitment_requests_target_user_id_users')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_recruitment_requests_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recruitment_requests'))
    )
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_in_team', sa.Enum('LEADER', 'MEMBER', name='teammemberrole', native_enum=False, length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_team_members_event_id_events')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_team_members_team_id_teams')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_team_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_team_members'))
    )
    op.create_index('uq_member_active_per_event', 'team_members', ['event_id', 'user_id'], unique=True, postgresql_where=sa.text('active'))
    op.create_index('uq_member_active_per_team', 'team_members', ['team_id', 'user_id'], unique=True, postgresql_where=sa.text('active'))
    op.create_table('tournaments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_game_id', sa.Integer(), nullable=False),
    sa.Column('challonge_url', sa.String(length=500), nullable=True),
    sa.Column('published_message_ref', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_game_id'], ['event_games.id'], name=op.f('fk_tournaments_event_game_id_event_games')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_tournaments_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tournaments')),
    sa.UniqueConstraint('event_game_id', name=op.f('uq_tournaments_event_game_id'))
    )
    op.create_table('application_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'ASSIGNED_TO_TEAM', 'DISQUALIFIED', name='applicationstatus', native_enum=False, length=24), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'WITHDRAWN', 'ASSIGNED_TO_TEAM', 'DISQUALIFIED', name='applicationstatus', native_enum=False, length=24), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_application_history_actor_user_id_users')),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_application_history_application_id_applications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_history'))
    )
    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('winner_team_id', sa.Integer(), nullable=False),
    sa.Column('screenshot_url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reported_by', sa.Integer(), nullable=False),
    sa.Column('corrected', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_results_match_id_matches')),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], name=op.f('fk_match_results_reported_by_users')),
    sa.ForeignKeyConstraint(['winner_team_id'], ['teams.id'], name=op.f('fk_match_results_winner_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_results')),
    sa.UniqueConstraint('match_id', name=op.f('uq_match_results_match_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_results')
    op.drop_table('application_history')
    op.drop_table('tournaments')
    op.drop_index('uq_member_active_per_team', table_name='team_members', postgresql_where=sa.text('active'))
    op.drop_index('uq_member_active_per_event', table_name='team_members', postgresql_where=sa.text('active'))
    op.drop_table('team_members')
    op.drop_table('recruitment_requests')
    op.drop_table('mechanics')
    op.drop_table('matches')
    op.drop_table('checkins')
    op.drop_index('uq_app_active_per_user', table_name='applications', postgresql_where=sa.text("status IN ('PENDING','APPROVED','ASSIGNED_TO_TEAM')"))
    op.drop_index('uq_app_active_per_email', table_name='applications', postgresql_where=sa.text("status IN ('PENDING','APPROVED','ASSIGNED_TO_TEAM')"))
    op.drop_table('applications')
    op.drop_table('teams')
    op.drop_index('uq_staff_active', table_name='staff_assignments', postgresql_where=sa.text('active'))
    op.drop_table('staff_assignments')
    op.drop_table('recruitment_posts')
    op.drop_table('exports')
    op.drop_table('event_games')
    op.drop_index('ix_resource_lookup', table_name='discord_resources')
    op.drop_table('discord_resources')
    op.drop_index('ix_audit_event_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('games')
    op.drop_index('uq_events_active_per_guild', table_name='events', postgresql_where=sa.text("state <> 'ARCHIVED'"))
    op.drop_table('events')
    # ### end Alembic commands ###
